name: ScriptFlow
version: '0.0.1'
synopsis: An easy scripting language
description: Please see README.org
category: Development
author: Eleazar Díaz Delgado
maintainer: eleazardzdo@gmail.com
copyright: 2017 Eleazar Díaz Delgado
license: BSD3
github: none
extra-source-files:
  - README.md

library:
  source-dirs: src
  ghc-options: -Wall -Wno-orphans
  dependencies:
    - base
    - array
    - mtl
    - text
    - free
    - formatting
    - transformers
    - containers
    - unordered-containers
    - process
    - bytestring
    - microlens-platform
    - microlens-aeson
    - parsec
    - vector
    - template-haskell
    - haskeline
    - http-client
    - http-client-tls
    - aeson
    - yaml
  exposed-modules:
    - Compiler.Ast
    - Compiler.Core
    - Compiler.Interpreter.Types
    - Compiler.Interpreter.Methods
    - Compiler.Scope.Types
    - Compiler.Scope.Methods
    - Compiler.Object.Types
    - Compiler.Object.Methods
    - Compiler.Instruction.Types
    - Compiler.Instruction.Methods
    - Compiler.World.Types
    - Compiler.World.Methods
    - Compiler.Token.Types
    - Compiler.Token.Methods
    - Compiler.Parser.Types
    - Compiler.Parser.Methods

executables:
  Compiler:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -Wall
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - base
      - optparse-applicative
      - ScriptFlow

tests:
  Compiler-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -Wall
    dependencies:
      - ScriptFlow
      - base
      - hspec
      - megaparsec
