name: ScriptFlow
version: '0.0.3'
synopsis: An easy scripting language
description: Please see README.org
category: Development, Languages
author: Eleazar Díaz Delgado
maintainer: eleazardzdo@gmail.com
copyright: 2018 Eleazar Díaz Delgado
license: BSD3
github: ULL-ESIT-GRADOII-TFG/TFG-Eleazar-18
extra-source-files:
  - README.org
  - defaultConfig.yaml
  - templates/AlexTemplate
  - templates/AlexTemplate-ghc
  - templates/AlexTemplate-ghc-nopred
  - templates/AlexWrapper-monadUserState-bytestring
build-type: Custom

custom-setup:
  dependencies:
    - base
    - Cabal

library:
  source-dirs: src
  build-tools: alex
  ghc-options: -Wall -Wno-orphans
  dependencies:
    - aeson
    - array
    - base
    - bytestring
    - containers
    - unordered-containers
    - data-default
    - directory
    - filepath
    - free
    - haskeline
    - http-client
    - http-client-tls
    - include-file
    - microlens-aeson
    - microlens-platform
    - mtl
    - parsec
    - pcre-light
    - prettyprinter
    - process
    - scientific
    - template-haskell
    - text
    - vector
    - yaml
  exposed-modules:
    - Compiler.Ast
    - Compiler.Config
    - Compiler.Core
    - Compiler.Error
    - Compiler.Identifier
    - Compiler.Instruction
    - Compiler.Interpreter.Command
    - Compiler.Interpreter.Evaluate
    - Compiler.Object
    - Compiler.Object.OBool
    - Compiler.Object.ODouble
    - Compiler.Object.ONum
    - Compiler.Object.ORegex
    - Compiler.Object.OShellCommand
    - Compiler.Object.OStr
    - Compiler.Object.OVector
    - Compiler.Parser.Utils
    - Compiler.Parser.Methods
    - Compiler.Parser.Types
    - Compiler.Prelude
    - Compiler.Prelude.Th
    - Compiler.Prelude.Utils
    - Compiler.Prettify
    - Compiler.Scope
    - Compiler.Token.Lexer
    - Compiler.Token.LexerGen
    - Compiler.Token.Methods
    - Compiler.Token.Types
    - Compiler.Types
    - Compiler.Utils
    - Compiler.World

executables:
  scriptflow:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -Wall
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - base
      - optparse-applicative
      - ScriptFlow

tests:
  Compiler-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -Wall
    dependencies:
      - ScriptFlow
      - base
      - hspec
      - parsec
      - vector
      - bytestring
