name: ScriptFlow
version: '0.0.1'
synopsis: An easy scripting language
description: Please see README.org
category: Development
author: Eleazar Díaz Delgado
maintainer: eleazardzdo@gmail.com
copyright: 2018 Eleazar Díaz Delgado
license: BSD3
github: none
extra-source-files:
  - README.md
  - defaultConfig.yaml

library:
  source-dirs: src
  build-tools: alex
  ghc-options: -Wall -Wno-orphans
  dependencies:
    - aeson
    - array
    - base
    - bytestring
    - containers
    - data-default
    - directory
    - filepath
    - formatting
    - free
    - groom
    - haskeline
    - include-file
    - http-client
    - http-client-tls
    - microlens-aeson
    - microlens-platform
    - mtl
    - parsec
    - process
    - template-haskell
    - text
    - transformers
    - unordered-containers
    - vector
    - yaml
  exposed-modules:
    - Compiler.Ast
    - Compiler.Types
    - Compiler.Config.Methods
    - Compiler.Config.Types
    - Compiler.Core.Methods
    - Compiler.Core.Types
    - Compiler.Instruction.Methods
    - Compiler.Instruction.Types
    - Compiler.Interpreter.Command.Methods
    - Compiler.Interpreter.Methods
    - Compiler.Interpreter.Types
    - Compiler.Interpreter.Utils
    - Compiler.Object.Methods
    - Compiler.Object.Types
    - Compiler.Parser.Methods
    - Compiler.Parser.Types
    - Compiler.Prelude.Methods
    - Compiler.Prelude.Types
    - Compiler.Prelude.Utils
    - Compiler.Prelude.OStr
    - Compiler.Prelude.OBool
    - Compiler.Prelude.ODouble
    - Compiler.Prelude.ONum
    - Compiler.Prelude.OVector
    - Compiler.Prelude.ODic
    - Compiler.Prelude.ORegex
    - Compiler.Prelude.OShellCommand
    - Compiler.Scope.Methods
    - Compiler.Scope.Types
    - Compiler.Token.Lexer
    - Compiler.Token.Methods
    - Compiler.Token.Types
    - Compiler.World.Methods
    - Compiler.World.Types

executables:
  scriptflow:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -Wall
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - base
      - optparse-applicative
      - ScriptFlow

tests:
  Compiler-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -Wall
    dependencies:
      - ScriptFlow
      - base
      - hspec
      - parsec
      - vector
