* ScriptFlow

  TODO: What is it?

** Installation

   Use Haskell Stack
   #+BEGIN_SRC bash
   cd TFG-Eleazar-18
   stack build
   stack exec scriptflow
   #+END_SRC

   To get help
   #+BEGIN_SRC bash
   stack exec scriptflow -- --help
   #+END_SRC

   Install to ./local/bin
   #+BEGIN_SRC bash
   stack install
   #+END_SRC

** Documentation
   See [[./docs/lang.org]]

** Work in Progress:

  - Usar FUSE para montar la API
    - Se necesita una ubicacion para el punto de montaje
    - Ubicación para los repositorios

  - No establecer las direcciones de los argumentos en las funciones al generar el scope. Aplazarlo al runtime.
  - El tema de lo errores se debe mejorar.
    - Los errores internos del compilador, deben producir version+commit y localizacion de lanzamiento de excepcion.
    - Los errores del codigo compilado deben consolidarse. E imprimir correctamente la seccion y localizacion, Como un texto informativo del error

  - Implementar el config dentro del interprete
    - Pensar una forma de realizar interpolación de cadenas
      - Requiere un tipo nuevo LStr ([Object] -> String)
      - Se puede obviar por el momento construir un método interno para
        propósito específico

  - Realizar las comunicaciones con el API de Github
    - Mediante el propio lenguaje o de forma interna

**  License
   The 3-Clause BSD License
